// <auto-generated />
using System;
using EduConnect.Api.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EduConnect.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416064926_ExpandNotificationConstraintsForLeave")]
    partial class ExpandNotificationConstraintsForLeave
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.AttachmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entity_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_attachments_school_id");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("ix_attachments_uploaded_at")
                        .HasFilter("entity_id IS NULL");

                    b.HasIndex("UploadedById")
                        .HasDatabaseName("ix_attachments_uploaded_by_id");

                    b.HasIndex("EntityId", "EntityType")
                        .HasDatabaseName("ix_attachments_entity");

                    b.ToTable("attachments", null, t =>
                        {
                            t.HasCheckConstraint("chk_attachment_content_type", "content_type IN ('image/jpeg', 'image/png', 'image/webp', 'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')");

                            t.HasCheckConstraint("chk_attachment_entity_type", "entity_type IS NULL OR entity_type IN ('homework', 'notice')");

                            t.HasCheckConstraint("chk_attachment_size", "size_bytes > 0 AND size_bytes <= 10485760");
                        });
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.AttendanceRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnteredById")
                        .HasColumnType("uuid")
                        .HasColumnName("entered_by_id");

                    b.Property<string>("EnteredByRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entered_by_role");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_attendance_records");

                    b.HasIndex("EnteredById")
                        .HasDatabaseName("ix_attendance_records_entered_by_id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_attendance_records_school_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_attendance_records_student_id");

                    b.HasIndex("StudentId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_records_student_id_date")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("SchoolId", "StudentId", "Date")
                        .HasDatabaseName("ix_attendance_records_school_id_student_id_date");

                    b.ToTable("attendance_records", null, t =>
                        {
                            t.HasCheckConstraint("chk_attendance_entered_by_role", "entered_by_role IN ('Parent', 'Teacher', 'Admin')");

                            t.HasCheckConstraint("chk_attendance_status", "status IN ('Absent', 'Late')");
                        });
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.AuthResetTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("purpose");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_reset_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_auth_reset_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_reset_tokens_user_id");

                    b.HasIndex("UserId", "Purpose")
                        .HasDatabaseName("ix_auth_reset_tokens_user_id_purpose")
                        .HasFilter("used_at IS NULL");

                    b.ToTable("auth_reset_tokens", null, t =>
                        {
                            t.HasCheckConstraint("chk_auth_reset_purpose", "purpose IN ('Password', 'Pin')");
                        });
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.ClassEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("academic_year");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("section");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_classes");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_classes_school_id");

                    b.HasIndex("SchoolId", "Name", "Section", "AcademicYear")
                        .IsUnique()
                        .HasDatabaseName("ix_classes_school_id_name_section_academic_year");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.HomeworkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_id");

                    b.Property<Guid>("AssignedById")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEditable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_editable");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<Guid?>("RejectedById")
                        .HasColumnType("uuid")
                        .HasColumnName("rejected_by_id");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejected_reason");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_homework");

                    b.HasIndex("ApprovedById")
                        .HasDatabaseName("ix_homework_approved_by_id");

                    b.HasIndex("AssignedById")
                        .HasDatabaseName("ix_homework_assigned_by_id");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_homework_class_id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_homework_due_date");

                    b.HasIndex("RejectedById")
                        .HasDatabaseName("ix_homework_rejected_by_id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_homework_school_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_homework_status");

                    b.HasIndex("ClassId", "IsDeleted")
                        .HasDatabaseName("ix_homework_class_id_is_deleted")
                        .HasFilter("is_deleted = false");

                    b.ToTable("homework", null, t =>
                        {
                            t.HasCheckConstraint("chk_homework_status", "status IN ('Draft', 'PendingApproval', 'Published', 'Rejected')");
                        });
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.LeaveApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_id");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_leave_applications");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_leave_applications_parent_id");

                    b.HasIndex("ReviewedById")
                        .HasDatabaseName("ix_leave_applications_reviewed_by_id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_leave_applications_school_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_leave_applications_student_id");

                    b.HasIndex("SchoolId", "Status")
                        .HasDatabaseName("ix_leave_applications_school_id_status")
                        .HasFilter("is_deleted = false");

                    b.ToTable("leave_applications", null, t =>
                        {
                            t.HasCheckConstraint("chk_leave_applications_dates", "end_date >= start_date");

                            t.HasCheckConstraint("chk_leave_applications_status", "status IN ('Pending', 'Approved', 'Rejected')");
                        });
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.NoticeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("PublishedById")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_id");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_audience");

                    b.Property<Guid?>("TargetClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_class_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_notices");

                    b.HasIndex("PublishedById")
                        .HasDatabaseName("ix_notices_published_by_id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_notices_school_id");

                    b.HasIndex("TargetClassId")
                        .HasDatabaseName("ix_notices_target_class_id");

                    b.HasIndex("SchoolId", "IsPublished", "IsDeleted")
                        .HasDatabaseName("ix_notices_school_id_is_published_is_deleted")
                        .HasFilter("is_published = true AND is_deleted = false");

                    b.ToTable("notices", null, t =>
                        {
                            t.HasCheckConstraint("chk_notices_target_audience", "target_audience IN ('All', 'Class', 'Section')");
                        });
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_notifications_school_id");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_notifications_user_read_created");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("chk_notification_entity_type", "entity_type IS NULL OR entity_type IN ('notice', 'homework', 'attendance', 'leave_application')");

                            t.HasCheckConstraint("chk_notification_type", "type IN ('notice_published', 'homework_assigned', 'absence_marked', 'leave_applied')");
                        });
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.ParentStudentLinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("parent")
                        .HasColumnName("relationship");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_parent_student_links");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_parent_student_links_parent_id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_parent_student_links_school_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_parent_student_links_student_id");

                    b.HasIndex("ParentId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_parent_student_links_parent_id_student_id");

                    b.ToTable("parent_student_links", null, t =>
                        {
                            t.HasCheckConstraint("chk_parent_student_links_relationship", "relationship IN ('parent', 'guardian', 'grandparent', 'sibling', 'other')");
                        });
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.HasIndex("UserId", "IsRevoked")
                        .HasDatabaseName("ix_refresh_tokens_user_id_is_revoked")
                        .HasFilter("is_revoked = false");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.SchoolEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_schools");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_schools_code");

                    b.ToTable("schools", (string)null);
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.StudentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("roll_number");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_students_class_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_students_created_by");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_students_school_id");

                    b.HasIndex("SchoolId", "ClassId", "IsActive")
                        .HasDatabaseName("ix_students_school_class_active");

                    b.HasIndex("SchoolId", "ClassId", "RollNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_students_school_id_class_id_roll_number");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.SubjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id")
                        .HasName("pk_subjects");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_subjects_school_id");

                    b.HasIndex("SchoolId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_subjects_school_id_name");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.TeacherClassAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedById")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsClassTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_class_teacher");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("pk_teacher_class_assignments");

                    b.HasIndex("AssignedById")
                        .HasDatabaseName("ix_teacher_class_assignments_assigned_by");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_teacher_class_assignments_class_id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_teacher_class_assignments_school_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_teacher_class_assignments_teacher_id");

                    b.HasIndex("SchoolId", "ClassId")
                        .IsUnique()
                        .HasDatabaseName("ix_teacher_class_assignments_school_id_class_id")
                        .HasFilter("is_class_teacher = true");

                    b.HasIndex("TeacherId", "ClassId", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_teacher_class_assignments_teacher_id_class_id_subject");

                    b.ToTable("teacher_class_assignments", (string)null);
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PinHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pin_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_users_phone");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_users_school_id");

                    b.HasIndex("SchoolId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_school_id_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("SchoolId", "Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_users_school_id_phone");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("chk_users_role", "role IN ('Parent', 'Teacher', 'Admin')");
                        });
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.AttachmentEntity", b =>
                {
                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.SchoolEntity", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_schools_school_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_users_uploaded_by_id");

                    b.Navigation("School");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.AttendanceRecordEntity", b =>
                {
                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", "EnteredBy")
                        .WithMany()
                        .HasForeignKey("EnteredById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_records_users_entered_by_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.SchoolEntity", "School")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_records_schools_school_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.StudentEntity", "Student")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_records_students_student_id");

                    b.Navigation("EnteredBy");

                    b.Navigation("School");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.AuthResetTokenEntity", b =>
                {
                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_reset_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.ClassEntity", b =>
                {
                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.SchoolEntity", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_classes_schools_school_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.HomeworkEntity", b =>
                {
                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_homework_users_approved_by_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_homework_users_assigned_by_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.ClassEntity", "Class")
                        .WithMany("Homeworks")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_homework_classes_class_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", "RejectedBy")
                        .WithMany()
                        .HasForeignKey("RejectedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_homework_users_rejected_by_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.SchoolEntity", "School")
                        .WithMany("Homeworks")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_homework_schools_school_id");

                    b.Navigation("ApprovedBy");

                    b.Navigation("AssignedBy");

                    b.Navigation("Class");

                    b.Navigation("RejectedBy");

                    b.Navigation("School");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.LeaveApplicationEntity", b =>
                {
                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leave_applications_users_parent_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_leave_applications_users_reviewed_by_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.SchoolEntity", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leave_applications_schools_school_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.StudentEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leave_applications_students_student_id");

                    b.Navigation("Parent");

                    b.Navigation("ReviewedBy");

                    b.Navigation("School");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.NoticeEntity", b =>
                {
                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", "PublishedBy")
                        .WithMany()
                        .HasForeignKey("PublishedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notices_users_published_by_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.SchoolEntity", "School")
                        .WithMany("Notices")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notices_schools_school_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.ClassEntity", "TargetClass")
                        .WithMany("Notices")
                        .HasForeignKey("TargetClassId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notices_classes_target_class_id");

                    b.Navigation("PublishedBy");

                    b.Navigation("School");

                    b.Navigation("TargetClass");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.NotificationEntity", b =>
                {
                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.SchoolEntity", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_schools_school_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.ParentStudentLinkEntity", b =>
                {
                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parent_student_links_users_parent_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.SchoolEntity", "School")
                        .WithMany("ParentStudentLinks")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parent_student_links_schools_school_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.StudentEntity", "Student")
                        .WithMany("ParentLinks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parent_student_links_students_student_id");

                    b.Navigation("Parent");

                    b.Navigation("School");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.StudentEntity", b =>
                {
                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.ClassEntity", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_classes_class_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_students_users_created_by");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.SchoolEntity", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_schools_school_id");

                    b.Navigation("Class");

                    b.Navigation("CreatedBy");

                    b.Navigation("School");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.SubjectEntity", b =>
                {
                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.SchoolEntity", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subjects_schools_school_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.TeacherClassAssignmentEntity", b =>
                {
                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_teacher_class_assignments_users_assigned_by");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.ClassEntity", "Class")
                        .WithMany("TeacherClassAssignments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_class_assignments_classes_class_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.SchoolEntity", "School")
                        .WithMany("TeacherClassAssignments")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_class_assignments_schools_school_id");

                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_class_assignments_users_teacher_id");

                    b.Navigation("AssignedBy");

                    b.Navigation("Class");

                    b.Navigation("School");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", b =>
                {
                    b.HasOne("EduConnect.Api.Infrastructure.Database.Entities.SchoolEntity", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_schools_school_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.ClassEntity", b =>
                {
                    b.Navigation("Homeworks");

                    b.Navigation("Notices");

                    b.Navigation("Students");

                    b.Navigation("TeacherClassAssignments");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.SchoolEntity", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Classes");

                    b.Navigation("Homeworks");

                    b.Navigation("Notices");

                    b.Navigation("ParentStudentLinks");

                    b.Navigation("Students");

                    b.Navigation("TeacherClassAssignments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.StudentEntity", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("ParentLinks");
                });

            modelBuilder.Entity("EduConnect.Api.Infrastructure.Database.Entities.UserEntity", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
