// Superseded by 20260421082137_AddExams.cs, which is the canonical migration
// generated by `dotnet ef migrations add AddExams`. This file is intentionally
// empty — safe to delete from the filesystem. Left as a no-op file to avoid
// leaving a duplicate `AddExams` class that would break `dotnet build`.
